##
# Attempt at a common set of core tags for php web development.
#

---
- hosts: default
  user: root

  vars_files:
    - vars.global.yml
    - vars.project.yml

  tasks:
    ##
    # Apt package installation of required software.
    #
    - name: Packages | Install required packages.
      apt: pkg={{ item }} state=installed  update_cache=yes
      with_items: packages


    ##
    # Set Hostname
    #
    - hostname: name={{ server_hostname }}

    ##
    # Message of the day explaining server is under control of Ansible.
    #
    - name: General | Setting message of the day.
      template:
        src=templates/motd.j2
        dest=/etc/update-motd.d/95-ansible
        mode=755

    ##
    # PHP Setup.
    #
    - name: PHP | Configuration file, php.ini
      template:
        src=templates/etc-php5-apache2-php-ini.j2
        dest=/etc/php5/apache2/php.ini

    - name: APC | Cache configuration file, apc.ini
      template:
        src=templates/etc-php5-conf-d-apc-ini.j2
        dest=/etc/php5/conf.d/apc.ini

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file, my.cnf
      template:
        src=templates/etc-mysql-my-cnf.j2
        dest=/etc/mysql/my.cnf

    - name: MySQL | Check if MySQL was secured.
      stat: path=/var/mysql-secured
      register: mysqlsecured

    - name: Install MySQL Securely
      include: ./tasks/mysql-secure.yml
      when: not mysqlsecured.stat.exists

    - name: Setup | Install Composer
      shell: curl -sS https://getcomposer.org/installer | php;  mv composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer

    - name: Setup | Prepare composer directory
      file:
        path=/usr/share/composer
        state=directory

    - name: Setup | Install Drush
      shell: composer global require drush/drush:6.* -d /usr/share/composer; /usr/share/composer/vendor/bin/drush
      args:
        creates: /usr/share/composer/vendor/bin/drush

    - name: Setup | Add composer bin to path
      command: sed -i '1i export PATH="/usr/share/composer/vendor/bin:$PATH"' /etc/bash.bashrc

    ##
    # Apache2 setup.
    #
    - name: Apache | Enable some required modules
      command: a2enmod rewrite vhost_alias ssl

    - name: Apache | Configuration file for our site
      template:
        src=templates/etc-apache2-sites-available-devserver.j2
        dest=/etc/apache2/sites-available/devserver

    - name: Apache | Disable the default site
      command: a2dissite default

    - name: Apache | Enable our new site
      command: a2ensite devserver

    - name: SSH Keys | Save authorized_keys for local user to vagrant user
      authorized_key: user=vagrant key="{{ authorized_keys }}"

    ##
    # Restart services
    #
    - name: Restart Apache
      service:
        name=apache2
        state=started

    - name: Restart MySQL
      service:
        name=mysql
        state=started

    ##
    # Final Drupal Configuraiton
    #
    - name: Drupal | Create database user
      mysql_user:
        user={{ project }}
        password={{ project }}
        priv=*.*:ALL,GRANT
        state=present

    - name: Drupal | Create database
      mysql_db:
        db={{ project }}
        state=present

    - name: Drupal | Configuration folder, sites/{{ server_hostname }}
      file:
        path=/var/www/sites/{{ server_hostname }}
        state=directory

    - name: Drupal | Configuration file, settings.php
      template:
        src=templates/settings-php.j2
        dest=/var/www/sites/{{ server_hostname }}/settings.php

    - name: Drupal | Create files folder
      file:
        path=/var/www/sites/default/files
        state=directory

    - name: Drush | Create .drush folder
      file:
        path=/home/vagrant/.drush
        owner=vagrant
        group=vagrant
        state=directory

    - name: Drush | Create site alias on guest.
      template:
        src=templates/drush-alias-drushrc-php.j2
        dest=/home/vagrant/.drush/{{ project }}.alias.drushrc.php


    - name: Drush | Create drushrc file on guest.
      template:
        src=templates/drushrc-php.j2
        dest=/home/vagrant/.drush/drushrc.php

    ###
    # @TODO: Create a server wide site alias.

    ##
    # Install Drupal based on chosen profile
    # @TODO: This doesn't work.  Fails with ERROR: chdir is not a legal parameter in an Ansible task or handler, which
    #   is in direct opposition to the documentation.

#    - name: Drupal | Installation
#      shell: drush site-install {{ install_profile }}
#      chdir: /var/www/sites/{{ server_hostname }}
#      creates: /var/site-installed
#      tags: common
